---
host_packages_flatpak_flatpaks:
  - ca.desrt.dconf-editor
  - com.belmoussaoui.Obfuscate
  - com.bitwarden.desktop
  - com.github.tchx84.Flatseal
  - com.google.AndroidStudio
  - com.obsproject.Studio
  - com.rafaelmardojai.Blanket
  - com.valvesoftware.Steam
  - com.vscodium.codium
  - de.haeckerfelix.Fragments
  - dev.geopjr.Tuba                    # Mastodon client
  - im.fluffychat.Fluffychat
  - io.github.seadve.Kooha             # Screen recorder
  - io.missioncenter.MissionCenter
  - io.mpv.Mpv
  - md.obsidian.Obsidian
  - org.blender.Blender
  - org.chromium.Chromium
  - org.ghidra_sre.Ghidra
  - org.gimp.GIMP
  - org.gnome.Builder
  - org.gnome.Epiphany                 # GNOME Web
  - org.inkscape.Inkscape
  - org.jdownloader.JDownloader
  - org.keepassxc.KeePassXC
  - org.libreoffice.LibreOffice
  - org.mozilla.firefox
  - org.nmap.Zenmap
  - org.raspberrypi.rpi-imager
  - org.signal.Signal
  - org.torproject.torbrowser-launcher
  - org.zotero.Zotero
  - re.sonny.OhMySVG

host_packages_flatpak_alpaca:
  - com.jeffser.Alpaca
  - com.jeffser.Alpaca.Plugins.AMD     # AMD ROCm support for Alpaca
  - com.jeffser.Alpaca.Plugins.Ollama  # Install Ollama inside Alpaca (it can use external instances or other APIs but this is easiest)
...
